when:
  - event: cron
    branch: 13.0

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
       partial: false
       recursive: false

steps:
  - name: sync repo
    image: dangherve/owngit
    commands:
        - ./buildTools/rebase.sh
